# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 15:58
from __future__ import unicode_literals

import cite.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('hashtags', models.ManyToManyField(to='cite.CHashTag')),
            ],
        ),
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(storage=cite.models.GSFileSystemStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cquote',
            name='likers',
            field=models.ManyToManyField(related_name='liked_quotes', to='cite.CUser'),
        ),
        migrations.AddField(
            model_name='cquote',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_quotes', to='cite.CUser'),
        ),
    ]
