# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 16:06
from __future__ import unicode_literals

import cite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='avatar',
            field=models.ImageField(blank=True, storage=cite.models.GSFileSystemStorage(), upload_to=''),
        ),
    ]
