# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquote',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
