# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0002_auto_20160808_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquote',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='cite.CHashTag'),
        ),
        migrations.AlterField(
            model_name='cquote',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owned_quotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
