# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0003_auto_20160808_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cquote',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='cite.CHashTag'),
        ),
        migrations.AlterField(
            model_name='cquote',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
