# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0004_auto_20160808_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cquote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 12, 8, 7, 7, 729824, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cquote',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 12, 8, 7, 11, 297174, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
